version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - REDIS_HOST=redis
      - MODELSCOPE_TOKEN=${MODELSCOPE_TOKEN}
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./uploads:/app/uploads
    environment:
      - REDIS_HOST=redis
      - MODELSCOPE_TOKEN=${MODELSCOPE_TOKEN}
    depends_on:
      - redis 